### ISSUE TITLE
关于框架代码ALU中的一些疑问

### ISSUE THREAD

**Issue by pppppkun** [COA-2019/programming-answer#2]
在ALU.add中调用了adder，在adder中做了impleDigits，然后调用了carry_adder，然后在carry_adder中为什么又调用了impleDigits？
另外为啥有的地方使用StringBuilder有的地方使用了StringBuffer？

**Comment by pppppkun** [comment]
在ALU.add中调用了adder，在adder中做了impleDigits，然后调用了carry_adder，然后在carry_adder中为什么又调用了impleDigits？
另外为啥有的地方使用StringBuilder有的地方使用了StringBuffer？

**Comment by fraliphsoft** [comment]
对于问题一，是因为版本迭代导致的代码修改，原先在两次调用impleDigits之间会有一些额外操作，后来发现这些额外操作是不需要的，因此删除，导致两次调用impleDigits冗余
对于问题二，理论上使用StringBuilder会更为安全，但实际上对于现在这个"简陋"的模拟机器系统，两者是等效的，我们在分工编码时也没有对这些细节问题进行规范
以上两个问题都属于代码规范问题，由于同一段代码可能被不同助教修改过，或者由于代码修改的时间跨度，整个项目中都存在不少冗余代码，不仅仅是这两处。在后期整个框架基本成型后我们会考虑抽出时间对项目代码进行一次重构。
最后感谢同学的观察和反馈，以及抱歉昨天忙其他事看见后没有及时回复

**Comment by pppppkun** [comment]
在FPU里面使用遍历一个二维数组的方式来排除加减乘的特殊情况，但是实际上特殊情况的产生只和指数位是否全0或者全1相关，用if-else语句即可代替遍历，相应的，传入判断函数的只需要指数八位就行了，用乘法为栗子
如果此时检测到ope_src和opr_dest的指数都是0，则返回一个31为的0，然后根据对两个操作数的符号位进行异或操作然后返回即可
如果有一个不是0，那么表明两个操作数中有一个是INF，那么return NAN即可
如果不属于上述情况，return null
要是做这种更改，这需要在mul函数调用查询方法得到返回值后对返回值进行检查，如果是NUll，则进行运算，如果是NAN，直接返回，如果是31位的0，则加上符号位返回
对于add和sub时可以用相似的处理

不知道这样实现会不会好一些 @fraliphsoft

**Comment by fraliphsoft** [comment]
查表比if-else更利于阅读和理解，现在框架的做法是遍历表+遍历结果，你的建议在时间复杂度上等同于便利表，所以其实有一个更好的做法是将函数/对象作为表项，并提供一个通用接口进行结果返回，这样既能增强可读性，又能兼顾效率，但是代价就是设计成本的上升，而且这个简单的项目也没必要应用这些复杂的设计模式。
事实上，ALU采用的就是if-else进行特殊情况处理，有兴趣可以把ALU和FPU进行对比研究，不同的人应该会有不同的喜好。
最后，只传入8位指数是否足够取决于具体代码，也就是Inf和NaN的判断职责是在哪个方法中。
最后的最后，如果是improvement性质的问题，建议发送邮件或者留下姓名+学号，方便我们给出contributors

**Comment by pppppkun** [comment]
> 查表比if-else更利于阅读和理解，现在框架的做法是遍历表+遍历结果，你的建议在时间复杂度上等同于便利表，所以其实有一个更好的做法是将函数/对象作为表项，并提供一个通用接口进行结果返回，这样既能增强可读性，又能兼顾效率，但是代价就是设计成本的上升，而且这个简单的项目也没必要应用这些复杂的设计模式。
> 事实上，ALU采用的就是if-else进行特殊情况处理，有兴趣可以把ALU和FPU进行对比研究，不同的人应该会有不同的喜好。
> 最后，只传入8位指数是否足够取决于具体代码，也就是Inf和NaN的判断职责是在哪个方法中。
> 最后的最后，如果是improvement性质的问题，建议发送邮件或者留下姓名+学号，方便我们给出contributors

谢谢助教，另外FPU和ALU中有方法的重复（carry_adder、oneAdder、fullAdder、impleDigits），可以一起抽出来作为通用接口

**Comment by fraliphsoft** [comment]
是的 理论上全加器等东西都应该有专门的硬件单元，通用于整数和浮点数的二进制计算，但是这样会导致整个项目非常麻烦，有兴趣可以看看计科那边的机组大作业，有个较完整的cpp的框架(虽然和这门课的编程作业差别比较大)
(所以真的不考虑下姓名学号？(emoji404))

**Comment by pppppkun** [comment]
> 是的 理论上全加器等东西都应该有专门的硬件单元，通用于整数和浮点数的二进制计算，但是这样会导致整个项目非常麻烦，有兴趣可以看看计科那边的机组大作业，有个较完整的cpp的框架(虽然和这门课的编程作业差别比较大)
> (所以真的不考虑下姓名学号？(emoji404))

计科的实验做到3.1了
181250068 李淳
