### ISSUE TITLE
关于第五次作业的疑问

### ISSUE THREAD

**Issue by pppppkun** [COA-2019/programming-answer#3]

**Comment by pppppkun** [comment]
readme应该写错了吧
![image](https://user-images.githubusercontent.com/43557766/67784923-79b68d00-faa7-11e9-9e76-c274ac70e945.png)

**Comment by fraliphsoft** [comment]
是的 直接无视掉下面三行就好 周六发布到Moocoder的README会更新

**Comment by pppppkun** [comment]
> 是的 直接无视掉下面三行就好 周六发布到Moocoder的README会更新

写完了后发现替换策略里面的start和end只有在组相联的时候不是0-1024，是set*4和(set+1)*4，这个start和end原本是什么作用啊，还有我压根也没用到isHIt，判断是否命中在MappingStrategy里面的map就已经解决了= =
