### ISSUE TITLE
关于新用例的疑惑

### ISSUE THREAD

**Issue by QinRuixin** [COA-2019/programming-answer#7]
跳转指令的操作数是88，而剩下的指令长度只有88了，如果是offset的话，是否有问题

**Comment by pppppkun** [comment]
复议

**Comment by pppppkun** [comment]
附议

**Comment by QinRuixin** [comment]
如果根据上一次的框架，发生指令跳转时，跳转指令返回的长度应该是0，
那剩下的指令总长度是104
跳转指令的立即数也应该是96吧?

**Comment by zackBRAVE** [comment]
附议，而且eax怎么会是0呢

**Comment by fraliphsoft** [comment]
啊 才看见 最近比较忙 确实应该是96，eax是加一次之后的值 我先紧急改下seecoder

**Comment by fraliphsoft** [comment]
↑麻烦相互转告一下 顺便借楼说一下 第七次的答案过几天和第八次的答案一起公布

**Comment by QinRuixin** [comment]
已转告
