### ISSUE TITLE
关于MMU类中的toRealLinearAddr(String logicAddr)方法的疑惑

### ISSUE THREAD

**Issue by QinRuixin** [COA-2019/programming-answer#8]
为什么
实模式下的逻辑地址转线性地址
计算公式为：①(16-bits段寄存器左移4位 + offset的低16-bits) = 20-bits物理地址 ②高位补0到32-bits

**Comment by fraliphsoft** [comment]
关于为什么需要第二步：
实模式下的地址长度只有20-bits，这和地址线的总数有关。但是为了避免你们需要解析不同长度的地址，我们规定作业中的（物理）地址长度统一为32-bits，所以需要高位补0

关于第一步为什么要这么计算：
这个是i386给出的标准计算方式，具体为什么这么设计我也记不清了。。隐约记得葛季栋老师(操作系统)曾经提到过，好像和向前兼容有关(不确定 别信我)，有兴趣可以查点资料或者问问老师



546773427@qq.com
 
发件人： QinRuixin
发送时间： 2019-12-16 17:15
收件人： COA-2019/programming-answer
抄送： Subscribed
主题： [COA-2019/programming-answer] 关于MMU类中的toRealLinearAddr(String logicAddr)方法的疑惑 (#8)
为什么
实模式下的逻辑地址转线性地址
计算公式为：①(16-bits段寄存器左移4位 + offset的低16-bits) = 20-bits物理地址 ②高位补0到32-bits
―

**Comment by QinRuixin** [comment]
谢谢
