### ISSUE TITLE
FPU中的FPUHelper的floatDivision中注释是否有误

### ISSUE THREAD

**Issue by stormbroken** [COA-2019/programming-answer#9]
源码如下
String temp = unsignedDivision(Xsig, Ysig);  //这里不能用integerMultiplication，因为不是补码表示的除法，这个是无符号数的除法
其中integerMultiplication

**Comment by QinRuixin** [comment]
借楼顺带一提，ALU类中的carry_adder() 方法的注释中的放回值说明是否有误，进位已设置在CF中
    /**
     * add two nums with the length of given length which could be divided by 4, and the result's first bit presents the overflow
     * different from the {@code adder} method, the result's first bit presents whether it generates the carry
     *
     * @param operand1 first
     * @param operand2 second
     * @param c        original carray
     * @param length   given length
     * @return result, and the result's first bit presents the carry
     */
    private String carry_adder(String operand1, String operand2, char c, int length) {
        operand1 = impleDigits(operand1, length);
        operand2 = impleDigits(operand2, length);
        String res = "";
        char carry = c;
        for (int i = length - 1; i >= 0; i--) {  //这里length不一定是4的倍数，采用更加通用的加法算法
            String temp = fullAdder(operand1.charAt(i), operand2.charAt(i), carry);
            carry = temp.charAt(0);
            res = temp.charAt(1) + res;
        }
        CF = "" + carry;
        return res;  //注意这个方法里面溢出即有进位
    }

**Comment by fraliphsoft** [comment]
1. 作业版本存在较多更新，integerMultiplication应该是在某次更新后神秘失踪了，目测指的是ALU里的整数乘法。

2. 是的，返回的值是32位结果，不包含最高位进位。

相关错误注释已经删除，第八次考试结束后(的某一天)会同步到此git仓库
